In [1]:
import math
import numpy as np
np.set_printoptions(precision=3,suppress=True)

## Сингулярное разложение матриц

### 1. Найти с помощью NumPy SVD для матрицы

$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$  

#### Решение:

In [2]:
a = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

u, s, vh = np.linalg.svd(a, full_matrices=False)

v = vh.T
d = np.zeros_like(a, dtype=float)
d[np.diag_indices(min(a.shape))] = s

print(f'Матрица D:\n{d}\n')
print(f'Матрица U:\n{u}\n')
print(f'Матрица V:\n{v}\n')

Матрица D:
[[8.825 0.    0.   ]
 [0.    6.141 0.   ]
 [0.    0.    2.533]
 [0.    0.    0.   ]
 [0.    0.    0.   ]]

Матрица U:
[[ 0.171  0.157 -0.531]
 [ 0.393 -0.529  0.613]
 [-0.144 -0.824 -0.524]
 [ 0.888  0.061 -0.247]
 [ 0.081  0.108 -0.082]]

Матрица V:
[[ 0.071 -0.367 -0.927]
 [ 0.717  0.665 -0.208]
 [ 0.693 -0.65   0.311]]



### 2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.  
    
#### Решение:

In [3]:
s

array([8.825, 6.141, 2.533])

In [4]:
euc_norm = max(s)
fro_norm = math.sqrt(sum(map(lambda x: x ** 2, s))) # np.linalg.norm(a, ord='fro')

print(f'Евклидова норма: {euc_norm}\nНорма Фробениуса: {fro_norm}')

Евклидова норма: 8.824868854820448
Норма Фробениуса: 11.045361017187265
