In [1]:
import numpy as np

## Матрицы и матричные операции. Часть 1

### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [2]:
def check_matrices_ranges(a: [], b: []):
    return len(a[0]) == len(b)

In [3]:
def multiple_matrix_size(a: [], b: []):
    m = len(a)
    n = len(b[0])
    
    return (m, n)

In [4]:
def custom_sum(a: [], b: []):
    
    rows = len(a)
    cols = len(a[0])
    
    if rows != len(b) or cols != len(b[0]):
        print('Invalid matrices for sum')
        return None
    
    res = []
    
    for i in range(rows):
        res.append([])
        for j in range(cols):
            res[i].append(a[i][j] + b[i][j])
            
    return res

In [5]:
def custom_dot(a: [], b: []):
        
    if  not check_matrices_ranges:
        print('Invalid matrices for multiply')
        return None
        
    rows_b = len(b)
    rows_a, cols_b = multiple_matrix_size(a, b)    
        
    res = []        
    for i in range(rows_a):
        res.append([])
        for j in range(cols_b):
            res[i].append(0)            
            for k in range(rows_b):                
                res[i][j] += a[i][k] * b[k][j]
            
    return res

### 1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

In [6]:
print(f'''
№\tA\tB\tAB\tBA
а)\t4x2\t4x2\t-\t-
б)\t2x5\t5x3\t2x3\t-
в)\t8x3\t3x8\t8x8\t3x3
г)\t4x4\t4x4\t4x4\t4x4
''')


№	A	B	AB	BA
а)	4x2	4x2	-	-
б)	2x5	5x3	2x3	-
в)	8x3	3x8	8x8	3x3
г)	4x4	4x4	4x4	4x4



### 2. Найти сумму и произведение матриц
$\displaystyle A=\begin{pmatrix}
1 & -2\\
3 & 0
\end{pmatrix}$
 и 
$\displaystyle B=\begin{pmatrix}
4 & -1\\
0 & 5
\end{pmatrix}$

In [7]:
a = [[1, -2], [3, 0]]
b = [[4, -1], [0, 5]]

amount = custom_sum(a, b)
prod = custom_dot(a, b)

print(f'A + B = {amount}\nA x B = {prod}')

A + B = [[5, -3], [3, 5]]
A x B = [[4, -11], [12, -3]]


### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A−2B+4C  для матриц  
$\displaystyle A=\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix}$
,
$\displaystyle B=\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix}$
 и 
 $\displaystyle C=\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix}$

In [8]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

3 * a - 2 * b + 4 * c

array([[ 11,  -5],
       [  9, -12]])

### 4. Дана матрица  
$\displaystyle A=\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end{pmatrix}$. 
Вычислить $\displaystyle AA^T $ и $\displaystyle A^TA $.

In [9]:
a = np.array([[4, 1], [5, -2], [2, 3]])

a.dot(a.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [10]:
a.T.dot(a)

array([[45,  0],
       [ 0, 14]])

## Матрицы и матричные операции. Часть 2

### 1. Вычислить определитель:
а) $\displaystyle \begin{vmatrix}
\sin x & -\cos x\\
\cos x & \sin x
\end{vmatrix}$  

б) $\displaystyle \begin{vmatrix}
4 & 2 & 3\\
0 & 5 & 1\\
0 & 0 & 9
\end{vmatrix}$  

в) $\displaystyle \begin{vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{vmatrix}$  

#### Решение:
а)
$ \displaystyle \begin{pmatrix}
\sin x & -\cos x\\
\cos x & \sin x
\end{pmatrix} \cdot \begin{pmatrix}
\sin x & \cos x\\
-\cos x & \sin x
\end{pmatrix} =\begin{pmatrix}
\sin x\cdot \sin x+( -\cos x) \cdot ( -\cos x) & \sin x\cdot \cos x+( -\cos x) \cdot \sin x\\
\cos x\cdot \sin x+\sin x\cdot ( -\cos x) & \sin x\cdot \sin x+\cos x\cdot \cos x
\end{pmatrix} =\begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}$  
#### det = 1 (из свойства ортогональной матрицы)

In [11]:
# б)
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'det = {np.linalg.det(b)}')

det = 180.0


в)$\displaystyle \begin{vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{vmatrix} =\begin{vmatrix}
1 & 2 & 3\\
1 & 2 & 3\\
7 & 8 & 9
\end{vmatrix} +\begin{vmatrix}
1 & 2 & 3\\
3 & 3 & 3\\
7 & 8 & 9
\end{vmatrix} =0+\begin{vmatrix}
1 & 2 & 3\\
3 & 3 & 3\\
1 & 2 & 3
\end{vmatrix} +\begin{vmatrix}
1 & 2 & 3\\
3 & 3 & 3\\
6 & 6 & 6
\end{vmatrix} =0$  
#### det = 0 

### 2. Определитель матрицы  A  равен  4 . Найти:

а)  $ \displaystyle det\left( A^{2}\right)$;

б)  $ \displaystyle det\left( A^{T}\right)$ ;

в)  $ \displaystyle det( 2A)$.

#### Решение:

a) $ \displaystyle det\left( A^{2}\right) =\det A\cdot \det A=16$  

б) $ \displaystyle det\left( A^{T}\right) =\det A=4$  

в) $ \displaystyle det( 2A) =2\cdot \det A=8$

### 3. Доказать, что матрица  
\begin{pmatrix}
-2 & 7 & -3\\
4 & -14 & 6\\
-3 & 7 & 13
\end{pmatrix}
### вырожденная.

#### Решение:  
$\displaystyle \begin{pmatrix}
-2 & 7 & -3\\
4 & -14 & 6\\
-3 & 7 & 13
\end{pmatrix} =-2\cdot \begin{pmatrix}
4 & -14 & 6\\
4 & -14 & 6\\
-3 & 7 & 13
\end{pmatrix} =0$

### 4. Найти ранг матрицы:  
а) $\displaystyle \begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
2 & 3 & 4
\end{pmatrix}$  

б) $\displaystyle \begin{pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3\\
2 & 3 & 5 & 6
\end{pmatrix}$

In [12]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'rank = {np.linalg.matrix_rank(a)}')

rank = 2


In [13]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'rank = {np.linalg.matrix_rank(b)}')

rank = 3
